Feature/ex 1
vseabra/sprint_2 pull request #1
Opened 2021-11-05 16:52 UTC by vseabra

2021-11-05 16:55 UTC, vseabra commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 5](https://trello.com/c/2YlnTv7U/216-exerc%C3%ADcio-5)

2021-11-05 21:31 UTC, matheus-yudi-helpper requested changes

2021-11-05 21:31 UTC, matheus-yudi-helpper commented on src/ex_1/src/ex_1.ts
> +export class vowelCounter {
Procure utilizar `PascalCase` no nome de classes. 

Sugestão: Você poderia nomear o método como `count`* apenas, pois como a classe leva o nome Vowels, subentende-se que irá contar vogais. Da mesma forma que `Person.getName` e não `Person.getPersonName`, por exemplo.

2021-11-05 21:31 UTC, matheus-yudi-helpper commented on src/ex_1/src/ex_1.ts
> +  static countVowels(str: string): number {
Evitar abreviação na declaração de parâmetros, funções e variáveis.

2021-11-05 21:31 UTC, matheus-yudi-helpper commented on src/ex_1/src/main.ts
> +// exemplo de uso com a a palavra recebida por input em um form
Corrigir o comentário.

2021-11-05 21:31 UTC, matheus-yudi-helpper commented on src/ex_1/src/ex_1.ts
> +    const vowelsInString: string[] = lowerCaseLetters.filter((letter: string) => this.VOWELS.includes(letter))
Apesar de também funcionar, o ideal aqui é acessar o VOWELS com `VowelCounter.VOWELS`;

2021-11-05 21:31 UTC, matheus-yudi-helpper commented on .eslintrc.js
> +    "@typescript-eslint/no-inferable-types": "off", // (ノಠ益ಠ)ノ
Pode remover o emoji kkkk.

2021-11-06 14:13 UTC, vseabra commented on src/ex_1/src/ex_1.ts
> +    const vowelsInString: string[] = lowerCaseLetters.filter((letter: string) => this.VOWELS.includes(letter))
Sim, eu tinha deixado como privado pra tentar garantir uma imutabilidade mas eu vi que existe o readonly

2021-11-06 14:14 UTC, vseabra commented on .eslintrc.js
> +    "@typescript-eslint/no-inferable-types": "off", // (ノಠ益ಠ)ノ
Nem o meu .eslintrc escapa (ノಠ益ಠ)ノ

2021-11-06 20:46 UTC, matheus-yudi-helpper approved these changes

2021-11-06 20:46 UTC, matheus-yudi-helpper approved these changes

2021-11-06 21:40 UTC, merged