Feature/ex 6
vseabra/sprint_2 pull request #2
Opened 2021-11-05 18:24 UTC by vseabra

2021-11-05 18:24 UTC, vseabra commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 6](https://trello.com/c/MqWO0xjv/213-exerc%C3%ADcio-6)

2021-11-05 22:29 UTC, matheus-yudi-helpper requested changes

2021-11-05 22:29 UTC, matheus-yudi-helpper commented on src/ex_6/src/main.ts
> +// não sou fã desse nome, mas fiquei sem idea.
Pode manter esse nome e remover o comentário.

2021-11-05 22:29 UTC, matheus-yudi-helpper commented on src/ex_6/src/main.ts
> +    const scientistToUpdate = this.scientists.find((scientist: Person) => scientist.id === id)
Adicionar o tipo.

2021-11-05 22:29 UTC, matheus-yudi-helpper commented on src/ex_6/src/main.ts
> +    }
O método não retorna void?

2021-11-05 22:29 UTC, matheus-yudi-helpper commented on src/ex_6/src/main.ts
> +    const scientist = this.scientists.find((scientist: Person) => scientist.id === id)
Adicionar o tipo.

2021-11-06 16:15 UTC, vseabra commented on src/ex_6/src/types.ts
> +}
Mas ai os campos name e bio deixariam de ser opcionais, não? eu pensei em fazer Partial<Exclude<IPerson, 'id'>> mas não sei se ficaria melhor.

2021-11-10 00:08 UTC, matheus-yudi-helpper commented on src/ex_6/src/types.ts
> +}
Pode deixar assim, ta tranquilo, mas do jeito que você sugeriu também funcionaria.

2021-11-10 00:26 UTC, matheus-yudi-helpper approved these changes

2021-11-10 00:34 UTC, merged