Feature/ex 7
vseabra/sprint_2 pull request #3
Opened 2021-11-06 17:22 UTC by vseabra

2021-11-06 17:25 UTC, vseabra commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 7](https://trello.com/c/rMG2wp8l/214-exerc%C3%ADcio-7)

2021-11-10 00:49 UTC, ErickSasaki requested changes

2021-11-10 00:49 UTC, ErickSasaki commented on src/ex_7/src/main.ts
> +  constructor(unfiltedList: any[]) {
Não é bom colocar código solto no construtor, idealmente o construtor vai ter apenas chamadas de funções, nesse caso pode criar uma função que limpa a lista e chamar ela no construtor.

2021-11-10 00:49 UTC, ErickSasaki commented on src/ex_7/src/imperative.ts
> +    for (let i: number = 0; i < this.list.length; i++) {
Observação:
O javascript tem formas mais fáceis de percorrer arrays, pode utilizar "for in" caso precise do index ou "for of" caso não precise, o for normal não é errado, mas é bom conhecer as formas mais atuais

2021-11-10 00:49 UTC, ErickSasaki commented on src/ex_7/src/imperative.ts
> +export default NumericListImperative
Observação:
Você pode utilizar apenas "export class NumericListImperative" ao criar a classe pra poder importa-la em outros lugares, fazendo dessa forma evita esse export default no final das classes

2021-11-10 00:49 UTC, ErickSasaki commented on src/ex_7/src/examples.ts
> +import NumericList from "./main"
Faltou ponto e vírgula no final das instruções, comentários nas funções e níveis de acesso nos métodos e atributos (private / protected / public), caso tenha dúvidas sobre níveis de acesso e encapsulamento em POO da uma olhada aqui:
https://blog.betrybe.com/tecnologia/encapsulamento/

2021-11-10 01:43 UTC, vseabra commented on src/ex_7/src/main.ts
> +  constructor(unfiltedList: any[]) {
Corrigido

2021-11-10 01:44 UTC, vseabra commented on src/ex_7/src/imperative.ts
> +export default NumericListImperative
eu já conhecia isso, mas existe algum consenso de qual é o melhor jeito? eu acho que fica mais organizado colocar um export {a,b,c} ou export default no final do arquivo mesmo, principalmente pq quando eu for importar o default export eu não tenho que colocar o nome dele entre {}. 
De qualquer forma eu mudei coloquei o export antes das classe, mas não tenho grande preferência por um jeito ou outro.

2021-11-10 01:52 UTC, vseabra commented on src/ex_7/src/examples.ts
> +import NumericList from "./main"
eu não tinha colocado comentário pq achei que os metódos eram meio triviais...
```
  /**
   * retorna o menor valor da lista
   *
   * @returns o menor valor da lista
   */
  public get smallest(): number {
    return Math.min(...this.list);
  }
```
o comentário ficou maior que a função e não adicionou nada =/

also, essa parte de colocar o nível de acesso em todos os atributos é convenção ou é que nem tipar tudo no bootcamp? pq pelo que eu vi se eu não especificar o nível de acesso o padrão é public, então eu so tava especificando o que não devia ser public.

2021-11-10 21:42 UTC, matheus-yudi-helpper approved these changes

2021-11-11 20:32 UTC, merged