Feature/ex 8
vseabra/sprint_2 pull request #4
Opened 2021-11-08 12:25 UTC by vseabra

2021-11-08 12:26 UTC, vseabra commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 8](https://trello.com/c/rVNHrt5x/215-exerc%C3%ADcio-8)

2021-11-10 01:26 UTC, matheus-yudi-helpper requested changes

2021-11-10 01:26 UTC, matheus-yudi-helpper commented on src/ex_8/src/main.ts
> +  get contribution() {
Pode manter esse nome.

2021-11-11 01:34 UTC, ErickSasaki requested changes

2021-11-11 01:34 UTC, ErickSasaki commented on src/ex_8/src/example.ts
> +import { PersonFactory, IPerson, Scientist } from "./main"
Faltou colocar o ; no fim das instruções, pode parecer bobo mas é importante que a gente pegue hábitos de padronizar o código.

2021-11-11 01:34 UTC, ErickSasaki commented on src/ex_8/src/main.ts
> +  public get contribution() {
Faltou tipar retorno da função

2021-11-11 01:34 UTC, ErickSasaki commented on src/ex_8/src/main.ts
> +  public static createOne(person: IPerson): Scientist  {
Como você comentou, acho que ficaria legal colocar um exemplo mais complexo da factory, poderia fazer uma classe para cada cientista onde você verificaria pelo nome, só pra demonstrar o uso da factory mesmo, ou se tiver alguma outra ideia, manda bala

2021-11-11 14:51 UTC, vseabra commented on src/ex_8/src/main.ts
> +  public static createOne(person: IPerson): Scientist  {
Blz, eu fiz uma classe para cada tipo de scientista (matematico, astronomo etc) e a factory faz um regex na bio para determinar a classe certa.

2021-11-12 00:39 UTC, ErickSasaki approved these changes

2021-11-12 00:39 UTC, merged